name: ESP32

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update
      - name: Build test
        run: |
          mv examples/enigmaiot_led_flasher/enigmaiot_led_flasher.ino examples/enigmaiot_led_flasher/enigmaiot_led_flasher.cpp
          mv examples/enigmaiot_node/enigmaiot_node.ino examples/enigmaiot_node/enigmaiot_node.cpp
          mv examples/enigmaiot_node_msgpack/enigmaiot_node_msgpack.ino examples/enigmaiot_node_msgpack/enigmaiot_node_msgpack.cpp
          mv examples/enigmaiot_node_nonsleepy/enigmaiot_node_nonsleepy.ino examples/enigmaiot_node_nonsleepy/enigmaiot_node_nonsleepy.cpp
          mv examples/EnigmaIOT-Button-Controller/EnigmaIOT-Button-Controller.ino examples/EnigmaIOT-Button-Controller/EnigmaIOT-Button-Controller.cpp
          mv examples/EnigmaIOT-DashButton-Controller/EnigmaIOT-DashButton-Controller.ino examples/EnigmaIOT-DashButton-Controller/EnigmaIOT-DashButton-Controller.cpp
          mv examples/EnigmaIOTGatewayDummy/EnigmaIOTGatewayDummy.ino examples/EnigmaIOTGatewayDummy/EnigmaIOTGatewayDummy.cpp
          mv examples/EnigmaIOTGatewayMQTT/EnigmaIOTGatewayMQTT.ino examples/EnigmaIOTGatewayMQTT/EnigmaIOTGatewayMQTT.cpp
          mv examples/EnigmaIOT-Json-Controller-Template/EnigmaIOT-Json-Controller-Template.ino examples/EnigmaIOT-Json-Controller-Template/EnigmaIOT-Json-Controller-Template.cpp
          mv examples/EnigmaIOT-Led-Controller/EnigmaIOT-Led-Controller.ino examples/EnigmaIOT-Led-Controller/EnigmaIOT-Led-Controller.cpp
          mv examples/EnigmaIOT-Sensor-Controller/EnigmaIOT-Sensor-Controller.ino examples/EnigmaIOT-Sensor-Controller/EnigmaIOT-Sensor-Controller.cpp
          mv examples/EnigmaIOT-SmartSwitch-Controller/EnigmaIOT-SmartSwitch-Controller.ino examples/EnigmaIOT-SmartSwitch-Controller/EnigmaIOT-SmartSwitch-Controller.cpp
          pio run -e esp32-MQTTGateway-SSL -e esp32-MQTTGateway-NoSSL -e esp32-DummyGateway -e esp32-Node -e esp32-NodeLedFlasher -e esp32-NodeMsgPack -e esp32-NodeNonSleepy -e esp32-ButtonController -e esp32-DashButtonController -e esp32-JsonControllerTemplate -e esp32-LedController -e esp32-SensorController -e esp32-SmartSwitchController
      
